# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)


Varietal.my_import('./data/varietals.csv')

country1 = Country.create(name: 'Argentina', bio: "bio", img_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/da/Argentine_wine_regions.jpg/350px-Argentine_wine_regions.jpg")
country2 = Country.create(name: 'Australia', bio: "bio", img_url: "https://www.foodandwine.com/sites/default/files/201003-a-australia-wine-regions.jpg")
country3 = Country.create(name: 'Austria', bio: "bio", img_url: "https://cellarhand.com.au/wp-content/uploads/2015/12/AUSTRIAN-WINE-MAP-1.jpg")
country4 = Country.create(name: 'Brazil', bio: "bio", img_url: "https://www.gobrazilwines.com/wp-content/uploads/2018/12/wines-of-brazil-map.jpg")
country5 = Country.create(name: 'Bulgaria', bio: "bio", img_url: "https://bulgarianwine.dk/wp-content/uploads/Wine-bulgaria-regions.png")
country6 = Country.create(name: 'Canada', bio: "bio", img_url: "http://www.wineandvinesearch.com/canada/canada.png")
country7 = Country.create(name: 'Chile', bio: "bio", img_url: "https://winefolly-wpengine.netdna-ssl.com/wp-content/uploads/2016/11/chilean-carmenere-best-wine-map.jpg")
country8 = Country.create(name: 'Croatia', bio: "bio", img_url: "http://www.croatianfinewines.com/skin/frontend/default/cfw_special/images/media/regions_of_croatia/new_wine_regions_of_croatia_large.jpg")
country9 = Country.create(name: 'Czech Republic', bio: "bio", img_url: "https://www.czecot.com/pic/regiony/mapa-vino.jpg")
country10 = Country.create(name: 'England', bio: "bio", img_url: "https://winefolly-wpengine.netdna-ssl.com/wp-content/uploads/2012/08/england-wineries.jpg")
country11 = Country.create(name: 'France', bio: "bio", img_url: "https://payload.cargocollective.com/1/0/20503/10553322/france-wine-regions_670.jpg")
country12 = Country.create(name: 'Georgia', bio: "bio", img_url: "http://www.thelazyhunter.com/wp-content/uploads/2017/10/Georgia-1.png")
country13 = Country.create(name: 'Germany', bio: "bio", img_url: "https://i.pinimg.com/originals/17/f3/04/17f3041cbb3ee9e26dd94f1847f98dd3.png")
country14 = Country.create(name: 'Greece', bio: "bio", img_url: "https://vinumvine.files.wordpress.com/2012/12/greece-wine-map.jpg")
country15 = Country.create(name: 'Hungary', bio: "bio", img_url: "https://www.hungarianwinehouse.co.uk/wp-content/uploads/2015/12/regions2.jpg")
country16 = Country.create(name: 'India', bio: "bio", img_url: "https://i.pinimg.com/originals/af/72/82/af7282e05a82b865db06893561483fd8.jpg")
country17 = Country.create(name: 'Israel', bio: "bio", img_url: "https://damevino.files.wordpress.com/2014/01/israel.gif")
country18 = Country.create(name: 'Italy', bio: "bio", img_url: "http://www.vinegeek.com/wp-content/uploads/2011/06/IncomparabiliViniItaliani_AntoineCorbineau.jpg")
country19 = Country.create(name: 'Lebanon', bio: "bio", img_url: "https://cdn.brate.com/images/product?id=28770&owner=190&shape=square")
country20 = Country.create(name: 'Luxembourg', bio: "bio", img_url: "http://www.wineandvinesearch.com/luxembourg/luxembourg.png")
country21 = Country.create(name: 'Macedonia', bio: "bio", img_url: "https://experiencemacedonia.files.wordpress.com/2011/02/map-of-macedonia.png?w=500")
country22 = Country.create(name: 'Mexico', bio: "bio", img_url: "https://cityprintsmapart.com/wp-content/uploads/2017/02/wr_mex_1.jpg")
country23 = Country.create(name: 'Moldova', bio: "bio", img_url: "https://i.imgur.com/Bbj4qQN.jpg")
country24 = Country.create(name: 'Morocco', bio: "bio", img_url: "https://vinumvine.files.wordpress.com/2012/09/morocco-wine-map.jpg?w=720")
country25 = Country.create(name: 'New Zealand', bio: "bio", img_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6c/New_zealand_wine_map.svg/2000px-New_zealand_wine_map.svg.png")
country26 = Country.create(name: 'Peru', bio: "bio", img_url: "https://www.freeandeasytraveler.com/content/adventure-map/Map%20Peru_-1-variants/thumb.jpg")
country27 = Country.create(name: 'Portugal', bio: "bio", img_url: "http://blog.sunvil.co.uk/wp-content/uploads/2013/08/Portuguese-wines-branded.jpg")
country28 = Country.create(name: 'Romania', bio: "bio", img_url: "https://pbs.twimg.com/media/Cjd3yNkUUAQz5N5.png")
country29 = Country.create(name: 'Serbia', bio: "bio", img_url: "http://serbianwines.com/images/wine-regions.jpg")
country30 = Country.create(name: 'Slovenia', bio: "bio", img_url: "http://www.mattwalls.co.uk/wp-content/uploads/2012/06/Map1.jpg")
country31 = Country.create(name: 'South Africa', bio: "bio", img_url: "http://www.regencywines.com/wp-content/uploads/2015/07/south_african_wine_regions1.jpg")
country32 = Country.create(name: 'Spain', bio: "bio", img_url: "https://www.tripsavvy.com/thmb/LycydrNVMKe5rqUF5aFhVc-kZo4=/600x475/filters:fill(auto,1)/spain-portugal-wine-map-56a3a2455f9b58b7d0d2eac5.png")
country33 = Country.create(name: 'Switzerland', bio: "bio", img_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8b/Kantone_der_Schweiz.svg/500px-Kantone_der_Schweiz.svg.png")
country34 = Country.create(name: 'Turkey', bio: "bio", img_url: "http://www.winesofturkey.org/wp-content/uploads/2012/05/kavaklidere_h.jpg")
country35 = Country.create(name: 'Ukraine', bio: "bio", img_url: "http://www.wineandvinesearch.com/ukraine/ukraine.png")
country36 = Country.create(name: 'Uruguay', bio: "bio", img_url: "https://bubblyprofessor.files.wordpress.com/2015/11/uruguay-map.jpg")
country37 = Country.create(name: 'United States', bio: "bio", img_url: "https://static01.nyt.com/newsgraphics/2013/06/10/wine/cee6ef00993a2ff557062b67398e32f7bed9782a/images/fallback/us.png")

tn1 = TastingNote.create(name: "Bergamot")
tn2 = TastingNote.create(name: "Blackberry")
tn3 = TastingNote.create(name: "Candied Fruit")
tn4 = TastingNote.create(name: "Cassis")
tn5 = TastingNote.create(name: "Cherry")
tn6 = TastingNote.create(name: "Citrus")
tn7 = TastingNote.create(name: "Coconut")
tn8 = TastingNote.create(name: "Cranberry")
tn9 = TastingNote.create(name: "Fig")
tn10 = TastingNote.create(name: "Gooseberries")
tn11 = TastingNote.create(name: "Green Apple")
tn12 = TastingNote.create(name: "Jammy")
tn13 = TastingNote.create(name: "Lychee")
tn14 = TastingNote.create(name: "Melon")
tn15 = TastingNote.create(name: "Passion Fruit")
tn16 = TastingNote.create(name: "Plum")
tn17 = TastingNote.create(name: "Strawberry")
tn18 = TastingNote.create(name: "Peach")
tn19 = TastingNote.create(name: "Balsamic")
tn20 = TastingNote.create(name: "Beetroot")
tn21 = TastingNote.create(name: "Black Pepper")
tn22 = TastingNote.create(name: "Chamomile")
tn23 = TastingNote.create(name: "Cedar")
tn24 = TastingNote.create(name: "Cinnamon")
tn25 = TastingNote.create(name: "Baking Spices")
tn26 = TastingNote.create(name: "Coffee")
tn27 = TastingNote.create(name: "Fennel")
tn28 = TastingNote.create(name: "Grass")
tn29 = TastingNote.create(name: "Green Pepper")
tn30 = TastingNote.create(name: "Honeysuckle")
tn31 = TastingNote.create(name: "Jasmine")
tn32 = TastingNote.create(name: "Lemongrass")
tn33 = TastingNote.create(name: "Mushroom")
tn34 = TastingNote.create(name: "Rose")
tn35 = TastingNote.create(name: "Rubber")
tn36 = TastingNote.create(name: "Tobacco")
tn37 = TastingNote.create(name: "Vanilla")
tn38 = TastingNote.create(name: "Vegetal")
tn39 = TastingNote.create(name: "Brioche Bun")
tn40 = TastingNote.create(name: "Buttery")
tn41 = TastingNote.create(name: "Caramel")
tn42 = TastingNote.create(name: "Charcoal")
tn43 = TastingNote.create(name: "Chocolate")
tn44 = TastingNote.create(name: "Earthy")
tn45 = TastingNote.create(name: "Graphite")
tn46 = TastingNote.create(name: "Leather")
tn47 = TastingNote.create(name: "Marzipan")
tn48 = TastingNote.create(name: "Meat")
tn49 = TastingNote.create(name: "Mineral")
tn50 = TastingNote.create(name: "Silky")
tn51 = TastingNote.create(name: "Slate")
tn52 = TastingNote.create(name: "Smoky")
tn53 = TastingNote.create(name: "Toffee")
tn54 = TastingNote.create(name: "Hazelnut")
tn55 = TastingNote.create(name: "FLoral")
tn56 = TastingNote.create(name: "Oak")
tn57 = TastingNote.create(name: "Apricot")
tn58 = TastingNote.create(name: "Pine")
tn59 = TastingNote.create(name: "Licorice")
tn60 = TastingNote.create(name: "Grapefruit")
tn61 = TastingNote.create(name: "Truffles")


Wine.my_import('./data/Wines.csv')
