# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)


Varietal.my_import('./data/varietals.csv')

country1 = Country.create(name: 'Argentina', bio: "bio")
country2 = Country.create(name: 'Australia', bio: "bio")
country3 = Country.create(name: 'Austria', bio: "bio")
country4 = Country.create(name: 'Brazil', bio: "bio")
country5 = Country.create(name: 'Bulgaria', bio: "bio")
country6 = Country.create(name: 'Canada', bio: "bio")
country7 = Country.create(name: 'Chile', bio: "bio")
country8 = Country.create(name: 'Croatia', bio: "bio")
country9 = Country.create(name: 'Czech Republic', bio: "bio")
country10 = Country.create(name: 'England', bio: "bio")
country11 = Country.create(name: 'France', bio: "bio")
country12 = Country.create(name: 'Georgia', bio: "bio")
country13 = Country.create(name: 'Germany', bio: "bio")
country14 = Country.create(name: 'Greece', bio: "bio")
country15 = Country.create(name: 'Hungary', bio: "bio")
country16 = Country.create(name: 'India', bio: "bio")
country17 = Country.create(name: 'Israel', bio: "bio")
country18 = Country.create(name: 'Italy', bio: "bio")
country19 = Country.create(name: 'Lebanon', bio: "bio")
country20 = Country.create(name: 'Luxembourg', bio: "bio")
country21 = Country.create(name: 'Macedonia', bio: "bio")
country22 = Country.create(name: 'Mexico', bio: "bio")
country23 = Country.create(name: 'Moldova', bio: "bio")
country24 = Country.create(name: 'Morocco', bio: "bio")
country25 = Country.create(name: 'New Zealand', bio: "bio")
country26 = Country.create(name: 'Peru', bio: "bio")
country27 = Country.create(name: 'Portugal', bio: "bio")
country28 = Country.create(name: 'Romania', bio: "bio")
country29 = Country.create(name: 'Serbia', bio: "bio")
country30 = Country.create(name: 'Slovenia', bio: "bio")
country31 = Country.create(name: 'South Africa', bio: "bio")
country32 = Country.create(name: 'Spain', bio: "bio")
country33 = Country.create(name: 'Switzerland', bio: "bio")
country34 = Country.create(name: 'Turkey', bio: "bio")
country35 = Country.create(name: 'Ukraine', bio: "bio")
country36 = Country.create(name: 'Uruguay', bio: "bio")
country37 = Country.create(name: 'United States', bio: "bio")

Wine.my_import('./data/Wines.csv')
