# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)


Varietal.my_import('./data/varietals.csv')

country1 = Country.create(name: 'Argentina', bio: "bio", img_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/da/Argentine_wine_regions.jpg/350px-Argentine_wine_regions.jpg")
country2 = Country.create(name: 'Australia', bio: "bio", img_url: "https://www.foodandwine.com/sites/default/files/201003-a-australia-wine-regions.jpg")
country3 = Country.create(name: 'Austria', bio: "bio", img_url: "https://cellarhand.com.au/wp-content/uploads/2015/12/AUSTRIAN-WINE-MAP-1.jpg")
country4 = Country.create(name: 'Brazil', bio: "bio", img_url: "https://www.gobrazilwines.com/wp-content/uploads/2018/12/wines-of-brazil-map.jpg")
country5 = Country.create(name: 'Bulgaria', bio: "bio", img_url: "https://bulgarianwine.dk/wp-content/uploads/Wine-bulgaria-regions.png")
country6 = Country.create(name: 'Canada', bio: "bio", img_url: "http://www.wineandvinesearch.com/canada/canada.png")
country7 = Country.create(name: 'Chile', bio: "bio", img_url: "https://winefolly-wpengine.netdna-ssl.com/wp-content/uploads/2016/11/chilean-carmenere-best-wine-map.jpg")
country8 = Country.create(name: 'Croatia', bio: "bio", img_url: "http://www.croatianfinewines.com/skin/frontend/default/cfw_special/images/media/regions_of_croatia/new_wine_regions_of_croatia_large.jpg")
country9 = Country.create(name: 'Czech Republic', bio: "bio", img_url: "https://www.czecot.com/pic/regiony/mapa-vino.jpg")
country10 = Country.create(name: 'England', bio: "bio", img_url: "https://winefolly-wpengine.netdna-ssl.com/wp-content/uploads/2012/08/england-wineries.jpg")
country11 = Country.create(name: 'France', bio: "bio", img_url: "https://payload.cargocollective.com/1/0/20503/10553322/france-wine-regions_670.jpg")
country12 = Country.create(name: 'Georgia', bio: "bio", img_url: "http://www.thelazyhunter.com/wp-content/uploads/2017/10/Georgia-1.png")
country13 = Country.create(name: 'Germany', bio: "bio", img_url: "https://i.pinimg.com/originals/17/f3/04/17f3041cbb3ee9e26dd94f1847f98dd3.png")
country14 = Country.create(name: 'Greece', bio: "bio", img_url: "https://vinumvine.files.wordpress.com/2012/12/greece-wine-map.jpg")
country15 = Country.create(name: 'Hungary', bio: "bio", img_url: "https://www.hungarianwinehouse.co.uk/wp-content/uploads/2015/12/regions2.jpg")
country16 = Country.create(name: 'India', bio: "bio", img_url: "https://i.pinimg.com/originals/af/72/82/af7282e05a82b865db06893561483fd8.jpg")
country17 = Country.create(name: 'Israel', bio: "bio", img_url: "https://damevino.files.wordpress.com/2014/01/israel.gif")
country18 = Country.create(name: 'Italy', bio: "bio")
country19 = Country.create(name: 'Lebanon', bio: "bio")
country20 = Country.create(name: 'Luxembourg', bio: "bio")
country21 = Country.create(name: 'Macedonia', bio: "bio")
country22 = Country.create(name: 'Mexico', bio: "bio")
country23 = Country.create(name: 'Moldova', bio: "bio")
country24 = Country.create(name: 'Morocco', bio: "bio")
country25 = Country.create(name: 'New Zealand', bio: "bio")
country26 = Country.create(name: 'Peru', bio: "bio")
country27 = Country.create(name: 'Portugal', bio: "bio")
country28 = Country.create(name: 'Romania', bio: "bio")
country29 = Country.create(name: 'Serbia', bio: "bio")
country30 = Country.create(name: 'Slovenia', bio: "bio")
country31 = Country.create(name: 'South Africa', bio: "bio")
country32 = Country.create(name: 'Spain', bio: "bio")
country33 = Country.create(name: 'Switzerland', bio: "bio")
country34 = Country.create(name: 'Turkey', bio: "bio")
country35 = Country.create(name: 'Ukraine', bio: "bio")
country36 = Country.create(name: 'Uruguay', bio: "bio")
country37 = Country.create(name: 'United States', bio: "bio")

Wine.my_import('./data/Wines.csv')
